# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-01 20:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Browser_2016_10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ua', models.CharField(max_length=100, unique=True)),
                ('some_value', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Browser (2016/10)',
                'verbose_name_plural': 'Browser (2016/10)',
            },
        ),
        migrations.CreateModel(
            name='Browser_2016_11',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ua', models.CharField(max_length=100, unique=True)),
                ('some_value', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Browser (2016/11)',
                'verbose_name_plural': 'Browser (2016/11)',
            },
        ),
        migrations.CreateModel(
            name='Browser_2016_12',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ua', models.CharField(max_length=100, unique=True)),
                ('some_value', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Browser (2016/12)',
                'verbose_name_plural': 'Browser (2016/12)',
            },
        ),
        migrations.CreateModel(
            name='Browser_2017_01',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ua', models.CharField(max_length=100, unique=True)),
                ('some_value', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Browser (2017/01)',
                'verbose_name_plural': 'Browser (2017/01)',
            },
        ),
        migrations.CreateModel(
            name='Browser_2017_02',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ua', models.CharField(max_length=100, unique=True)),
                ('some_value', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Browser (2017/02)',
                'verbose_name_plural': 'Browser (2017/02)',
            },
        ),
        migrations.CreateModel(
            name='Browser_2017_03',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ua', models.CharField(max_length=100, unique=True)),
                ('some_value', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Browser (2017/03)',
                'verbose_name_plural': 'Browser (2017/03)',
            },
        ),
        migrations.CreateModel(
            name='Browser_2017_04',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ua', models.CharField(max_length=100, unique=True)),
                ('some_value', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Browser (2017/04)',
                'verbose_name_plural': 'Browser (2017/04)',
            },
        ),
        migrations.CreateModel(
            name='Browser_2017_05',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ua', models.CharField(max_length=100, unique=True)),
                ('some_value', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Browser (2017/05)',
                'verbose_name_plural': 'Browser (2017/05)',
            },
        ),
        migrations.CreateModel(
            name='Browser_2017_06',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ua', models.CharField(max_length=100, unique=True)),
                ('some_value', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Browser (2017/06)',
                'verbose_name_plural': 'Browser (2017/06)',
            },
        ),
        migrations.CreateModel(
            name='Browser_2017_07',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ua', models.CharField(max_length=100, unique=True)),
                ('some_value', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Browser (2017/07)',
                'verbose_name_plural': 'Browser (2017/07)',
            },
        ),
        migrations.CreateModel(
            name='Event_2016_10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('value', models.IntegerField(default=0)),
                ('browser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_set', to='datastore.Browser_2016_10')),
            ],
            options={
                'verbose_name': 'Event (2016/10)',
                'verbose_name_plural': 'Event (2016/10)',
            },
        ),
        migrations.CreateModel(
            name='Event_2016_11',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('value', models.IntegerField(default=0)),
                ('browser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_set', to='datastore.Browser_2016_11')),
            ],
            options={
                'verbose_name': 'Event (2016/11)',
                'verbose_name_plural': 'Event (2016/11)',
            },
        ),
        migrations.CreateModel(
            name='Event_2016_12',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('value', models.IntegerField(default=0)),
                ('browser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_set', to='datastore.Browser_2016_12')),
            ],
            options={
                'verbose_name': 'Event (2016/12)',
                'verbose_name_plural': 'Event (2016/12)',
            },
        ),
        migrations.CreateModel(
            name='Event_2017_01',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('value', models.IntegerField(default=0)),
                ('browser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_set', to='datastore.Browser_2017_01')),
            ],
            options={
                'verbose_name': 'Event (2017/01)',
                'verbose_name_plural': 'Event (2017/01)',
            },
        ),
        migrations.CreateModel(
            name='Event_2017_02',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('value', models.IntegerField(default=0)),
                ('browser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_set', to='datastore.Browser_2017_02')),
            ],
            options={
                'verbose_name': 'Event (2017/02)',
                'verbose_name_plural': 'Event (2017/02)',
            },
        ),
        migrations.CreateModel(
            name='Event_2017_03',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('value', models.IntegerField(default=0)),
                ('browser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_set', to='datastore.Browser_2017_03')),
            ],
            options={
                'verbose_name': 'Event (2017/03)',
                'verbose_name_plural': 'Event (2017/03)',
            },
        ),
        migrations.CreateModel(
            name='Event_2017_04',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('value', models.IntegerField(default=0)),
                ('browser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_set', to='datastore.Browser_2017_04')),
            ],
            options={
                'verbose_name': 'Event (2017/04)',
                'verbose_name_plural': 'Event (2017/04)',
            },
        ),
        migrations.CreateModel(
            name='Event_2017_05',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('value', models.IntegerField(default=0)),
                ('browser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_set', to='datastore.Browser_2017_05')),
            ],
            options={
                'verbose_name': 'Event (2017/05)',
                'verbose_name_plural': 'Event (2017/05)',
            },
        ),
        migrations.CreateModel(
            name='Event_2017_06',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('value', models.IntegerField(default=0)),
                ('browser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_set', to='datastore.Browser_2017_06')),
            ],
            options={
                'verbose_name': 'Event (2017/06)',
                'verbose_name_plural': 'Event (2017/06)',
            },
        ),
        migrations.CreateModel(
            name='Event_2017_07',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('value', models.IntegerField(default=0)),
                ('browser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_set', to='datastore.Browser_2017_07')),
            ],
            options={
                'verbose_name': 'Event (2017/07)',
                'verbose_name_plural': 'Event (2017/07)',
            },
        ),
    ]
