# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-31 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Browser_2016_10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ua', models.CharField(max_length=100)),
                ('some_value', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Browser_2016_10',
                'verbose_name_plural': 'Browser_2016_10',
            },
        ),
        migrations.CreateModel(
            name='Browser_2016_11',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ua', models.CharField(max_length=100)),
                ('some_value', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Browser_2016_11',
                'verbose_name_plural': 'Browser_2016_11',
            },
        ),
        migrations.CreateModel(
            name='Browser_2016_12',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ua', models.CharField(max_length=100)),
                ('some_value', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Browser_2016_12',
                'verbose_name_plural': 'Browser_2016_12',
            },
        ),
        migrations.CreateModel(
            name='Browser_2017_01',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ua', models.CharField(max_length=100)),
                ('some_value', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Browser_2017_01',
                'verbose_name_plural': 'Browser_2017_01',
            },
        ),
        migrations.CreateModel(
            name='Browser_2017_02',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ua', models.CharField(max_length=100)),
                ('some_value', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Browser_2017_02',
                'verbose_name_plural': 'Browser_2017_02',
            },
        ),
        migrations.CreateModel(
            name='Browser_2017_03',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ua', models.CharField(max_length=100)),
                ('some_value', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Browser_2017_03',
                'verbose_name_plural': 'Browser_2017_03',
            },
        ),
        migrations.CreateModel(
            name='Browser_2017_04',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ua', models.CharField(max_length=100)),
                ('some_value', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Browser_2017_04',
                'verbose_name_plural': 'Browser_2017_04',
            },
        ),
        migrations.CreateModel(
            name='Browser_2017_05',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ua', models.CharField(max_length=100)),
                ('some_value', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Browser_2017_05',
                'verbose_name_plural': 'Browser_2017_05',
            },
        ),
        migrations.CreateModel(
            name='Browser_2017_06',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ua', models.CharField(max_length=100)),
                ('some_value', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Browser_2017_06',
                'verbose_name_plural': 'Browser_2017_06',
            },
        ),
        migrations.CreateModel(
            name='Event_2016_10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('value', models.IntegerField()),
                ('browser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.Browser_2016_10')),
            ],
            options={
                'verbose_name': 'Event_2016_10',
                'verbose_name_plural': 'Event_2016_10',
            },
        ),
        migrations.CreateModel(
            name='Event_2016_11',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('value', models.IntegerField()),
                ('browser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.Browser_2016_11')),
            ],
            options={
                'verbose_name': 'Event_2016_11',
                'verbose_name_plural': 'Event_2016_11',
            },
        ),
        migrations.CreateModel(
            name='Event_2016_12',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('value', models.IntegerField()),
                ('browser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.Browser_2016_12')),
            ],
            options={
                'verbose_name': 'Event_2016_12',
                'verbose_name_plural': 'Event_2016_12',
            },
        ),
        migrations.CreateModel(
            name='Event_2017_01',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('value', models.IntegerField()),
                ('browser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.Browser_2017_01')),
            ],
            options={
                'verbose_name': 'Event_2017_01',
                'verbose_name_plural': 'Event_2017_01',
            },
        ),
        migrations.CreateModel(
            name='Event_2017_02',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('value', models.IntegerField()),
                ('browser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.Browser_2017_02')),
            ],
            options={
                'verbose_name': 'Event_2017_02',
                'verbose_name_plural': 'Event_2017_02',
            },
        ),
        migrations.CreateModel(
            name='Event_2017_03',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('value', models.IntegerField()),
                ('browser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.Browser_2017_03')),
            ],
            options={
                'verbose_name': 'Event_2017_03',
                'verbose_name_plural': 'Event_2017_03',
            },
        ),
        migrations.CreateModel(
            name='Event_2017_04',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('value', models.IntegerField()),
                ('browser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.Browser_2017_04')),
            ],
            options={
                'verbose_name': 'Event_2017_04',
                'verbose_name_plural': 'Event_2017_04',
            },
        ),
        migrations.CreateModel(
            name='Event_2017_05',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('value', models.IntegerField()),
                ('browser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.Browser_2017_05')),
            ],
            options={
                'verbose_name': 'Event_2017_05',
                'verbose_name_plural': 'Event_2017_05',
            },
        ),
        migrations.CreateModel(
            name='Event_2017_06',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('value', models.IntegerField()),
                ('browser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.Browser_2017_06')),
            ],
            options={
                'verbose_name': 'Event_2017_06',
                'verbose_name_plural': 'Event_2017_06',
            },
        ),
    ]
