# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-23 16:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action_p0',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('some_value', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Action (part 0)',
                'verbose_name_plural': 'Action (part 0)',
            },
        ),
        migrations.CreateModel(
            name='Action_p1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('some_value', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Action (part 1)',
                'verbose_name_plural': 'Action (part 1)',
            },
        ),
        migrations.CreateModel(
            name='Action_p2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('some_value', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Action (part 2)',
                'verbose_name_plural': 'Action (part 2)',
            },
        ),
        migrations.CreateModel(
            name='Action_p3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('some_value', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Action (part 3)',
                'verbose_name_plural': 'Action (part 3)',
            },
        ),
        migrations.CreateModel(
            name='Action_p4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('some_value', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Action (part 4)',
                'verbose_name_plural': 'Action (part 4)',
            },
        ),
        migrations.CreateModel(
            name='Session_p0',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Session (part 0)',
                'verbose_name_plural': 'Session (part 0)',
            },
        ),
        migrations.CreateModel(
            name='Session_p1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Session (part 1)',
                'verbose_name_plural': 'Session (part 1)',
            },
        ),
        migrations.CreateModel(
            name='Session_p2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Session (part 2)',
                'verbose_name_plural': 'Session (part 2)',
            },
        ),
        migrations.CreateModel(
            name='Session_p3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Session (part 3)',
                'verbose_name_plural': 'Session (part 3)',
            },
        ),
        migrations.CreateModel(
            name='Session_p4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Session (part 4)',
                'verbose_name_plural': 'Session (part 4)',
            },
        ),
        migrations.AddField(
            model_name='action_p4',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_set', to='datastore.Session_p4'),
        ),
        migrations.AddField(
            model_name='action_p3',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_set', to='datastore.Session_p3'),
        ),
        migrations.AddField(
            model_name='action_p2',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_set', to='datastore.Session_p2'),
        ),
        migrations.AddField(
            model_name='action_p1',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_set', to='datastore.Session_p1'),
        ),
        migrations.AddField(
            model_name='action_p0',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_set', to='datastore.Session_p0'),
        ),
    ]
